Comment out old tests from CI
Signed-off-by: Piotr Piotrowski <piotr@synadia.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -36,45 +36,45 @@ jobs:
                 find . -type f -name "*.go" | xargs misspell -error -locale US
                 golangci-lint run --timeout 5m0s ./jetstream/...
 
-    test:
-        runs-on: ubuntu-latest-8-cores
+    # test:
+    #     runs-on: ubuntu-latest-8-cores
 
-        strategy:
-            matrix:
-              go: [ "1.25", "1.26" ]
-              include:
-                - go: "1.26"
-                  coverage: true
-        steps:
-            - name: Checkout code
-              uses: actions/checkout@v6
+    #     strategy:
+    #         matrix:
+    #           go: [ "1.25", "1.26" ]
+    #           include:
+    #             - go: "1.26"
+    #               coverage: true
+    #     steps:
+    #         - name: Checkout code
+    #           uses: actions/checkout@v6
       
-            - name: Setup Go
-              uses: actions/setup-go@v6
-              with:
-                go-version: ${{ matrix.go }}
+    #         - name: Setup Go
+    #           uses: actions/setup-go@v6
+    #           with:
+    #             go-version: ${{ matrix.go }}
 
-            - name: Install deps
-              shell: bash --noprofile --norc -x -eo pipefail {0}
-              run: |
-                go install github.com/mattn/goveralls@latest
-                go install github.com/wadey/gocovmerge@latest
+    #         - name: Install deps
+    #           shell: bash --noprofile --norc -x -eo pipefail {0}
+    #           run: |
+    #             go install github.com/mattn/goveralls@latest
+    #             go install github.com/wadey/gocovmerge@latest
 
-            - name: Test and coverage
-              shell: bash --noprofile --norc -x -eo pipefail {0}
-              run: |
-                go test -modfile=go_test.mod -v -run=TestNoRace -p=1 ./... --failfast -vet=off
-                if [ "${{ matrix.coverage }}" = "true" ]; then
-                  ./scripts/cov.sh CI
-                else
-                  go test -modfile=go_test.mod -race -v -p=1 ./... --failfast -vet=off -tags=internal_testing
-                fi
+    #         - name: Test and coverage
+    #           shell: bash --noprofile --norc -x -eo pipefail {0}
+    #           run: |
+    #             go test -modfile=go_test.mod -v -run=TestNoRace -p=1 ./... --failfast -vet=off
+    #             if [ "${{ matrix.coverage }}" = "true" ]; then
+    #               ./scripts/cov.sh CI
+    #             else
+    #               go test -modfile=go_test.mod -race -v -p=1 ./... --failfast -vet=off -tags=internal_testing
+    #             fi
 
-            - name: Coveralls
-              if: matrix.coverage
-              uses: coverallsapp/github-action@v2
-              with:
-               file: acc.out
+    #         - name: Coveralls
+    #           if: matrix.coverage
+    #           uses: coverallsapp/github-action@v2
+    #           with:
+    #            file: acc.out
 
     test-tester:
         runs-on: ubuntu-latest
